allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  058ed099-ef3a-463e-9814-c9567e5a478b:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:cd83fc3f-a9c0-4d33-8779-b35f92b6d574'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-28T17:28:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7995da79-9780-4f46-8c81-13d8219eed0c # Ceinture
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5178e065-702c-4e37-bd65-f380374f8908
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-12T14:41:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 83c8b547-d334-479b-8790-6073227cf239 # Date et heure
            handle: null
            instructions: null
            label: 'Date de victoire'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd83fc3f-a9c0-4d33-8779-b35f92b6d574
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-28T17:28:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: de1cb108-8395-45f0-9a7e-8648a6b295b1 # Date de perte
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e79fef4-4945-4728-9dca-89ae94f05891
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 8485ff01-dd06-43b6-945c-d2b22b1d688d
        userCondition: null
    thumbFieldKey: null
handle: championships
hasTitleField: false
icon: medal
name: Palmarès
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
