allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  3e0d7325-aa5f-4918-9754-47224996ce6a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-08T16:10:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4c887764-9c33-4b69-b237-d030b020c64b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-08T21:11:54+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ff2f36b2-53d4-4ffa-94bc-dafac093ba77 # Titre Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 893f58be-a3ca-4f36-9d8d-ca1bab748a4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-08T21:11:54+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 698c46e3-2baa-4914-9a5b-0c7f94fdc345 # Description Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 310b199d-0cfc-487d-9dac-564811246ca6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-12T14:52:56+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f4857798-fbf9-40c6-9e25-be024d571f66 # Photo Principale
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b963818-a01e-4295-b237-e51c97fe5139
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-08T21:11:54+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 137b7ddb-c95b-4e06-8cfc-1aa66be68441 # Reseaux Sociaux
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54c136bd-8e5d-4df4-96d6-38828f52850a
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 0ee87cec-2290-46d6-80aa-79b3f2796984
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-05T09:47:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7a5940b8-874a-46b3-828d-0b57d2795971 # Articles à la une
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 942a9c27-b568-45a8-86ce-77c3062e3a1e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-05T09:50:23+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3968a9ee-b747-4ac5-8dc3-92d1e382da48 # Afficher derniers articles
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fe6aa06-56b6-4947-928c-3092e2a64af9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-05T10:22:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 455a1610-d31f-4a00-8929-3a430acab4a1 # Clips à la une
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2024e5cc-d61b-4cfb-b9fe-9e4cfe4c85dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-05T10:22:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b9bbbe7b-4d2f-4730-be61-7c979b4f6762 # Afficher derniers clips
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de9c849c-6b4b-4b78-9582-0f67890d3ef4
            userCondition: null
            warning: null
            width: 100
        name: 'Article et clips'
        uid: 8a8bf853-fe03-4d52-b14b-323ed967b94b
        userCondition: null
    thumbFieldKey: null
handle: pageAccueil
hasTitleField: true
icon: house
name: 'Page Accueil'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
