columnSuffix: null
handle: alignment
instructions: null
name: 'Status (Face/Heel)'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Face
        -
          - value
          - face
        -
          - icon
          - thumbs-up
        -
          - color
          - '#00ff00'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Heel
        -
          - value
          - heel
        -
          - icon
          - thumbs-down
        -
          - color
          - '#ff0000'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Tweener
        -
          - value
          - tweener
        -
          - icon
          - face-meh
        -
          - color
          - '#c0c0c0'
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
