columnSuffix: null
handle: basicLink
instructions: null
name: Lien
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
  types:
    - url
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
