columnSuffix: null
handle: heroDescription
instructions: null
name: 'Description Hero'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  ckeConfig: 17d2cdef-6126-4860-b9b7-efd2fd907c7c # Simple
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
