columnSuffix: null
handle: hometown
instructions: null
name: "Ville d'origine"
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Ex : "Lyon"'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
