columnSuffix: null
handle: shortDescription
instructions: null
name: 'Description Courte'
searchable: false
settings:
  byteLimit: null
  charLimit: 200
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
