dateModified: 1772299732
email:
  fromEmail: anteur.ap@gmail.com
  fromName: sly-verse
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    0a309741-d071-40a8-96d8-0d27616f63d6: 'Image ceinture' # Image ceinture
    0b13dee1-11a9-4890-9396-d9d8ebabaeb1: 'Planning de stream' # Planning de stream
    1d063901-7cb3-4c79-915e-22ba059582e9: 'Show associé' # Show associé
    2ed97ddf-9e6c-40ff-91bc-edeaaaff1dcf: 'Contenu riche' # Contenu riche
    3a16fde8-1283-4270-9152-47a67599c43b: Images # Images
    3d7f00c7-52ff-4d8d-9751-516d1d2031e3: Shows # Shows
    3da03560-0cdd-49dd-841c-1f93fed92c25: 'Titre du match' # Titre du match
    3e1c5ada-e455-476e-a1c9-8f739eeb9dce: 'Nom de ring' # Nom de ring
    4f2c6aeb-7270-46d9-9cc2-4c61dff9cfb3: Roster # Roster
    5dd8b7cd-49eb-45ee-8908-71aa8d1af97b: 'Type de media' # Type de media
    5f2cb259-f127-4914-9959-1be5198ce79c: Resultat # Resultat
    6da1a3b6-9cc2-475e-b48e-c326a587677e: Superstars # Superstars
    6ee001c3-016d-4f6e-af69-22fcf05a862a: 'Cartes des matchs' # Cartes des matchs
    7b732697-7d7a-4f5f-be43-3a24fd228288: Palmarès # Palmarès
    7c15e95d-31ed-4f61-9610-77235b8dcad7: 'Prochains Streams' # Prochains Streams
    9c4b88e0-4999-445c-b5cf-1ff8fcf50d22: Shows # Shows
    9d4ead9a-be68-4068-8951-d44d1242f7f6: "Ville d'origine" # Ville d'origine
    9d821b57-8cd2-4cac-8997-29b5d7fe1d72: 'Lien interne' # Lien interne
    9ed251ed-f16f-42d7-8807-5ad4e2143b12: 'Type de match' # Type de match
    17d2cdef-6126-4860-b9b7-efd2fd907c7c: Simple # Simple
    23f8f2ea-3312-4fde-b78f-91af2c6b4d08: Lien # Lien
    36f6ab6e-3dba-42ce-8dc5-f767b1e3e70e: 'Image Lien' # Image Lien
    43f6fe78-d1df-49c6-92cc-4e3fecb73e26: 'Durée estimée' # Durée estimée
    46fbcf79-d0f1-4aad-a7c9-b699f446122c: 'Type de lien' # Type de lien
    83c8b547-d334-479b-8790-6073227cf239: 'Date et heure' # Date et heure
    91fcfd3c-d8aa-45f9-8ee6-3620c987dd12: 'Menu principal' # Menu principal
    137b7ddb-c95b-4e06-8cfc-1aa66be68441: 'Reseaux Sociaux' # Reseaux Sociaux
    228e300a-4071-419a-b8ca-635beb87a64a: Ceinture # Ceinture
    320b0998-4777-4f7d-a3cf-657b89946d28: 'Type de show' # Type de show
    394ef542-7e6c-467e-a8b2-c825583a7602: Médiathèque # Médiathèque
    421b99f8-110b-4e5f-9fcb-dd00a1b61d41: Genre # Genre
    435eaa9f-6b5b-4f4d-84eb-d1504c07dd73: Note # Note
    571ebbef-2a72-4f6b-84d1-6efecad99596: 'Sly Wresling Universe' # Sly Wresling Universe
    698c46e3-2baa-4914-9a5b-0c7f94fdc345: 'Description Hero' # Description Hero
    841b05cb-aaca-4ce8-91d0-c7e1a4ed809d: Ceinture # Ceinture
    0895fb55-d909-451b-af8b-ec803acc70d3: 'Page Accueil' # Page Accueil
    950e9bc0-fd03-413f-a144-64e282958f13: Vainqueur # Vainqueur
    3835ca37-9fef-4fd0-b183-3837223d3c71: "Pays d'origine" # Pays d'origine
    03997ee4-22b0-493c-a976-adce138d48aa: 'Prochain streams' # Prochain streams
    4479b21e-82c5-4ad9-b095-a75b4b1e09a3: Superstar # Superstar
    6436a9a5-863e-44e1-88b4-477f06146ed4: 'Page Accueil' # Page Accueil
    7995da79-9780-4f46-8c81-13d8219eed0c: Ceinture # Ceinture
    9080e8ef-3d35-4a29-929f-cd4d82c30e6b: 'Public Schema' # Public Schema
    9981bc2e-03e8-4889-ab40-96ddc496edd2: 'Lien externe' # Lien externe
    58492aea-1965-4454-a046-cd0abbafab76: 'Menu principal' # Menu principal
    59474f27-c591-4c21-8a13-c28330d316fe: 'Planning Streams' # Planning Streams
    156177ef-b718-4dfe-9d8b-dcd8eb5f98af: 'Description Courte' # Description Courte
    235945f3-c99a-4e44-972a-2e56c18f7843: 'Status (Face/Heel)' # Status (Face/Heel)
    2268121f-f160-477f-a8dd-097ac58ac120: 'Nombre de règnes' # Nombre de règnes
    a393ad5e-193d-4947-b8a4-8c76a120412c: sly-verse # sly-verse
    a349698f-8a90-4500-a74f-9fe7f44ac901: Libellé # Libellé
    aa3b6fc6-594b-4c1d-b7d2-456b44617bbc: 'Comment participer' # Comment participer
    af31a34b-be53-40aa-bd12-bc660d90950e: "Galerie d'images" # Galerie d'images
    b9f994df-9b3e-4505-a43b-0124c057887e: 'Statut actif/inactif' # Statut actif/inactif
    b786d593-d6e5-4df6-8f84-d6b51b741daa: Finisher # Finisher
    bd4c2f9c-ea7f-4ef7-8dfe-9d091b5db3f0: 'Statut du show' # Statut du show
    c469f72b-bb7d-4fb3-b855-ed34ccd6f73b: 'Image de profil' # Image de profil
    cf8271af-e15e-4b59-b37f-6067d46f7d7c: Poids # Poids
    d34dead9-c601-418a-b86a-9becaab8b175: howTo # howTo
    d84ac3fa-7b19-4233-8929-20ca20accc37: 'Carte des matchs' # Carte des matchs
    d135e597-391a-47a4-a188-9f9a0ae11542: 'Lien vidéo externe' # Lien vidéo externe
    d3567cd9-d874-4dcf-a4ad-9a2745ddee1a: 'Nom du titre' # Nom du titre
    d4597144-81d0-4a72-af9c-d7a544da4ee2: 'Réseaux Sociaux' # Réseaux Sociaux
    de005802-be42-430e-bf28-c16c101a5807: Mediathèque # Mediathèque
    de1cb108-8395-45f0-9a7e-8648a6b295b1: 'Date de perte' # Date de perte
    e04677af-3be7-4c6e-9e90-a8d20033b7db: Palmarès # Palmarès
    e4ab6bc4-aab9-4263-815b-238aba267fb5: Participants # Participants
    e775c6ec-5d74-4213-8643-cac989a5fd98: Taille # Taille
    e6222976-8d28-4eb9-9eb4-ebcdc2f3d586: Navigation # Navigation
    f86e6bc1-0aef-44f6-a0c1-83f69929d250: Stipulation # Stipulation
    f4857798-fbf9-40c6-9e25-be024d571f66: 'Photo Principale' # Photo Principale
    ff2f36b2-53d4-4ffa-94bc-dafac093ba77: 'Titre Hero' # Titre Hero
plugins:
  admin-bar:
    edition: lite
    enabled: true
    schemaVersion: 3.1.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.14.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: sly-verse
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
