fieldLayouts:
  0a500888-f974-473a-8c08-1a2745f71adc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-12T15:36:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 91fcfd3c-d8aa-45f9-8ee6-3620c987dd12 # Menu principal
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83bb8a76-c3df-4da0-8a6b-5ea1a88758f8
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 4e8c4b4f-9b0c-433d-9723-70b611efd746
        userCondition: null
handle: navigation
name: Navigation
sortOrder: 1
