defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 698fdd99-cfe7-4e4c-a16f-dafe95a1953e # Clip
handle: clips
maxAuthors: 1
name: Clips
previewTargets:
  -
    label: 'Page d‘entrée primaire'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  571ebbef-2a72-4f6b-84d1-6efecad99596: # Sly Wresling Universe
    enabledByDefault: true
    hasUrls: true
    template: _pages/clips/_entry.twig
    uriFormat: 'clips/{slug}'
type: channel
